CREATE TABLE applications (
  id BIGSERIAL PRIMARY KEY,
  application_no VARCHAR(20) NOT NULL UNIQUE,
  applicant_id BIGINT NOT NULL REFERENCES users(id),
  title VARCHAR(100) NOT NULL,
  body TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
